# Broadcom switchdev modules

BRCM_SWITCHDEV_VERSION = 1.0.0.0 

BRCM_SWITCHDEV = switchdev-modules_$(BRCM_SWITCHDEV_VERSION)_amd64.deb
$(BRCM_SWITCHDEV)_SRC_PATH = $(PLATFORM_PATH)/switchdev
$(BRCM_SWITCHDEV)_DEPENDS += $(LINUX_HEADERS_HWE) $(LINUX_HEADERS) $(LINUX_HEADERS_COMMON)
$(BRCM_SWITCHDEV)_BUILD_ENV += PKG_NAME=$(BRCM_SWITCHDEV)
$(BRCM_SWITCHDEV)_MACHINE = broadcom
SONIC_DPKG_DEBS += $(BRCM_SWITCHDEV)

