# Docker base image (based on Debian Bookworm)

DOCKER_BASE_JAMMY = docker-base-jammy.gz
$(DOCKER_BASE_JAMMY)_PATH = $(DOCKERS_PATH)/docker-base-jammy

$(DOCKER_BASE_JAMMY)_DEPENDS += $(SOCAT)

GDB = gdb
GDBSERVER = gdbserver
VIM = vim
OPENSSH = openssh-client
SSHPASS = sshpass
STRACE = strace

ifeq ($(INCLUDE_FIPS), y)
$(DOCKER_BASE_JAMMY)_DEPENDS += $(FIPS_OPENSSL_LIBSSL) $(FIPS_OPENSSL_LIBSSL_DEV) $(FIPS_OPENSSL) $(SYMCRYPT_OPENSSL) $(FIPS_KRB5)
endif

$(DOCKER_BASE_JAMMY)_DBG_IMAGE_PACKAGES += $(GDB) $(GDBSERVER) $(VIM) $(OPENSSH) $(SSHPASS) $(STRACE)

SONIC_DOCKER_IMAGES += $(DOCKER_BASE_JAMMY)
SONIC_JAMMY_DOCKERS += $(DOCKER_BASE_JAMMY)
