# noble-based docker image for sonic swss layer

DOCKER_SWSS_LAYER_NOBLE= docker-swss-layer-noble.gz
$(DOCKER_SWSS_LAYER_NOBLE)_PATH = $(DOCKERS_PATH)/docker-swss-layer-noble

$(DOCKER_SWSS_LAYER_NOBLE)_DEPENDS += $(SWSS)
$(DOCKER_SWSS_LAYER_NOBLE)_LOAD_DOCKERS += $(DOCKER_CONFIG_ENGINE_NOBLE)

$(DOCKER_SWSS_LAYER_NOBLE)_DBG_DEPENDS = $($(DOCKER_CONFIG_ENGINE_NOBLE)_DBG_DEPENDS) \
                                             $(SWSS_DBG)
$(DOCKER_SWSS_LAYER_NOBLE)_DBG_IMAGE_PACKAGES = $($(DOCKER_CONFIG_ENGINE_NOBLE)_DBG_IMAGE_PACKAGES)

SONIC_DOCKER_IMAGES += $(DOCKER_SWSS_LAYER_NOBLE)
SONIC_NOBLE_DOCKERS += $(DOCKER_SWSS_LAYER_NOBLE)
