# Docker base image (based on Debian Bookworm)

DOCKER_BASE_NOBLE = docker-base-noble.gz
$(DOCKER_BASE_NOBLE)_PATH = $(DOCKERS_PATH)/docker-base-noble

$(DOCKER_BASE_NOBLE)_DEPENDS += $(SOCAT)

GDB = gdb
GDBSERVER = gdbserver
VIM = vim
OPENSSH = openssh-client
SSHPASS = sshpass
STRACE = strace

ifeq ($(INCLUDE_FIPS), y)
$(DOCKER_BASE_NOBLE)_DEPENDS += $(FIPS_OPENSSL_LIBSSL) $(FIPS_OPENSSL_LIBSSL_DEV) $(FIPS_OPENSSL) $(SYMCRYPT_OPENSSL) $(FIPS_KRB5)
endif

$(DOCKER_BASE_NOBLE)_DBG_IMAGE_PACKAGES += $(GDB) $(GDBSERVER) $(VIM) $(OPENSSH) $(SSHPASS) $(STRACE)

SONIC_DOCKER_IMAGES += $(DOCKER_BASE_NOBLE)
SONIC_NOBLE_DOCKERS += $(DOCKER_BASE_NOBLE)
